set -g default-terminal "tmux-256color"

# Hotkey for reloading the config
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# Set new panes to open in current directory
# https://gist.github.com/william8th/faf23d311fc842be698a1d80737d9631
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
